# Generated by Django 5.2.9 on 2025-12-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='active_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
