# Generated by Django 5.2.9 on 2025-12-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_directory_active_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='active_at',
            field=models.DateTimeField(null=True),
        ),
    ]
